### ISSUE TITLE
pages/index

### ISSUE THREAD

**Issue by mjyoung** [skylarw19/w-chakra-ui-nextjs#3]
Noticed a few things:

1. Should probably disable the Search button if there is no input or if the input is only spacebars. Otherwise the API throws an error when you try to search.

2. https://github.com/skylarw19/w-chakra-ui-nextjs/blob/df2b3268ba1e8287752f6ec5b10b3e4877a36bd4/src/pages/index.js#L18 The state variable `search` is not very descriptive and does not convey the intent appropriately. Something like `hasSearched` and `setHasSearched` probably makes more sense. In general, when naming variables with `boolean` values, we want to prefix the variable using [modal verbs](http://esl.fis.edu/grammar/rules/modal.htm).

3. https://github.com/skylarw19/w-chakra-ui-nextjs/blob/df2b3268ba1e8287752f6ec5b10b3e4877a36bd4/src/pages/index.js#L50 React will want you to use a `key` prop when iterating over lists and rendering. Probably makes sense to get the `id` from the API and use that as the key value.

4. https://github.com/skylarw19/w-chakra-ui-nextjs/blob/df2b3268ba1e8287752f6ec5b10b3e4877a36bd4/src/pages/index.js#L50-L82 Minor but might be a good idea to refactor these into a `ShowCard` component. Again minor since we aren't necessarily reusing it anywhere, but if you end up using visual component libraries like [Storybook](https://storybook.js.org/) it is helpful to have these as their own component.

**Comment by skylarw19** [comment]
All done. Thanks for the comments!
